puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:pk>/", views.detail, name="detail"),
    path("new/<int:item_pk>/", views.new_conversation, name="new"),
]

puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForms
from .views import logout_view


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForms
        ),
        name="login",
    ),
    path("logout/", logout_view, name="logout"),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 

urlpatterns = [
    path("", include('core.urls')), 
    path('inbox/', include('conversation.urls')),
    path("items/", include("item.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/conversation/models.py
from django.db import models
from django.contrib.auth.models import User

from item.models import Item


class Conversation(models.Model):
    item = models.ForeignKey(
        Item, related_name="conversations", on_delete=models.CASCADE
    )
    members = models.ManyToManyField(User, related_name="conversations")
    criado_em = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [
            "-modified_at",
        ]


class ConversationMessage(models.Model):
    conversation = models.ForeignKey(
        Conversation, related_name="messages", on_delete=models.CASCADE
    )
    mensagem = models.TextField()
    criado_em = models.DateTimeField(auto_now_add=True)
    criado_por = models.ForeignKey(
        User, related_name="created_messages", on_delete=models.CASCADE
    )

puddle/conversation/forms.py
from django import forms

from .models import ConversationMessage


class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ("mensagem",)
        widgets = {
            "mensagem": forms.Textarea(attrs={"class": "w-full py-4 px-6 rounded-lg border"}),
        }

puddle/conversation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from item.models import Item

from .models import Conversation
from .forms import ConversationMessageForm


@login_required
def new_conversation(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)

    if item.criado_por == request.user:
        return redirect("dashboard:index")

    conversations = Conversation.objects.filter(item=item).filter(
        members__in=[request.user.id]
    )

    if conversations:
        pass  # redirecionar para conversas

    if request.method == "POST":
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation = Conversation.objects.create(item=item)
            conversation.members.add(request.user)
            conversation.members.add(item.criado_por)
            conversation.save()

            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.criado_por = request.user
            conversation_message.save()

            return redirect("item:detail", pk=item_pk)

    else:
        form = ConversationMessageForm()

    return render(
        request,
        "conversation/new.html",
        {
            "form": form,
        },
    )


@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members__in=[request.user.id])

    return render(
        request,
        "conversation/inbox.html",
        {
            "conversations": conversations,
        },
    )


@login_required
def detail(request, pk):
    conversation = Conversation.objects.filter(members__in=[request.user.id]).get(pk=pk)

    return render(request, "conversation/detail.html", {"conversation": conversation})

puddle/conversation/templates/conversation/detail.html
{% extends 'core/base.html' %}


{% block title %}
    Mensagem
{% endblock title %}


{% block content %}
<h1 class="'mb-6 text-3xl">Mensagem</h1>

<div class="space-y-6">
    {% for message in conversation.messages.all %}

            <div class="p-6 px-4 mb-4 flex {% if message.criado_por != request.user %}bg-blue-100{% else %}bg-gray-100{% endif %} rounded-lg">
                <div>
                    <p class="mb-4"><strong>{{ message.criado_por.username }}</strong> @ {{ message.criado_em }}</p>
                    <p>{{ message.mensagem }}</p>
                </div>

            </div>

    {% endfor %}
</div>
{% endblock content %}

puddle/conversation/templates/conversation/inbox.html
{% extends 'core/base.html' %}


{% block title %}
Caixa de Entrada
{% endblock title %}


{% block content %}
<h1 class="'mb-6 text-3xl">Caixa de Entrada</h1>

<div class="space-y-6">
    {% for conversation in conversations %}
        <a href="{% url 'conversation:detail' conversation.id %}">
            <div class="p-6 px-4 mb-4 flex bg-gray-100 rounded-lg">
                <div class="pr-6">
                    <img src="{{ conversation.item.imagem.url }}" alt="" class="w-20 h-20 max-w-full rounded-lg">
                </div>
                <div>
                    
                    {% for member in conversation.members.all %}
                        {% if member != request.user %}
                            <p class="mb-4"><strong>{{ member.username }}</strong> | {{ conversation.modified_at }}</p>
                            <p>{{ conversation.item.nome }}</p>
                        {% endif %}
                    {% endfor %}
                        
                </div>    
            </div>
        </a>
    {% endfor %}
</div>
{% endblock content %}

puddle/conversation/templates/conversation/new.html
{% extends 'core/base.html' %}


{% block title %}
Nova Conversa
{% endblock title %}


{% block content %}
<h1 class="'mb-6 text-3xl">Nova Conversa</h1>

<form method="post" action=".">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <br>
    <button class="mx-auto block py-1 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
</form>
{% endblock content %}