puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:pk>/", views.detail, name="detail"),
    path("new/<int:item_pk>/", views.new_conversation, name="new"),
]

puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForms
from .views import logout_view


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForms
        ),
        name="login",
    ),
    path("logout/", logout_view, name="logout"),
]

puddle/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

puddle/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
] 

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 

urlpatterns = [
    path("", include('core.urls')), 
    path('inbox/', include('conversation.urls')),
    path("items/", include("item.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForms(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Digite seu usuário",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Seu melhor e-mail",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Digite sua senha",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "confirme sua senha",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

class LoginForms(AuthenticationForm):  
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Digite seu usuário",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Digite sua senha",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Categoria, Item
from django.contrib.auth import logout
from django.shortcuts import redirect

from .forms import SignupForms


def index(request):
    items = Item.objects.filter(foi_vendido=False)[0:6]
    categories = Categoria.objects.all()

    return render(
        request,
        "core/index.html",
        {
            "categories": categories,
            "items": items,
        },
    )


def contact(request):
    return render(request, "core/contact.html")


def signup(request):
    if request.method == "POST":
        form = SignupForms(request.POST)

        if form.is_valid():
            form.save()
            return redirect("/login/")

    else:
        form = SignupForms()

    return render(request, "core/signup.html", {"form": form})


def logout_view(request):
    logout(request)

    return redirect("/login/")


def usuario_logado(request):
    return render(request, "core/usuario_logado.html", {"user": request.user})

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
        {% block title %}

        {% endblock title %}
        | Mercadinho
    </title>
</head>

<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-medium hover:text-gray-500">Mercadinho</a>
        <div class="space-x-6">
            
            <a href="{% url 'item:items' %}" 
                class="text-sm font-light hover:text-gray-500">Buscar</a>
                
            <a href="{% url 'item:new' %}" 
                class="text-sm font-light hover:text-gray-500">Vender</a>

            {% if request.user.is_authenticated %}       
                <a href="#"
                    class="text-sm font-semibold hover:text-gray-500">Bem-vindo, {{user.username}}</a>                    

                <a href="{% url 'conversation:inbox' %}"
                    class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Caixa de entrada</a>
                
                <a href="{% url 'dashboard:index' %}"
                    class="px-6 py-2 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                
                <a href="{% url 'core:logout' %}"
                    class="px-6 py-2 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Sair</a>
                
            {% else %}
                <a href="{% url 'core:signup' %}"
                    class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Registrar</a>
                <a href="{% url 'core:login' %}"
                    class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}

        </div>
    </nav>
    <div class="px-6 py-6">

        {% block content %}

        {% endblock content %}

    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">Sobre</h3>

            <p class="text-lg text-gray-300">New Little Tiger LTDA</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="list-reset">
                <li><a href="#" class="text-teal-500 hover:text-teal-700">Sobre</a></li>
                <li><a href=" {% url 'core:contact' %}" class="text-teal-500 hover:text-teal-700">Contato</a></li>
                <li><a href="#" class="text-teal-500 hover:text-teal-700">Política de Privacidade</a></li>
                <li><a href="#" class="text-teal-500 hover:text-teal-700">Termos de Uso</a></li>
            </ul>

        </div>
    </footer>
</body>

</html>

puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}
    Contato
{% endblock title %}

{% block content %}
    <h1>Contact Page</h1>
{% endblock content %}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-left">Ofertas do dia</h2>

    <style>
        /* Estilos CSS */
        .image-container {
            height: 200px;
            /* Defina a altura desejada */
            overflow: hidden;
        }

        .product-image {
            width: 100%;
            height: auto;
            display: block;
            object-fit: fill;
            /* Isso garante que a imagem seja cortada para caber no contêiner */
        }
    </style>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div class="image-container">
                    <img src="{{ item.imagem.url }}" class="product-image" alt="{{item.nome}}">
                </div>

                <div class="p-6 bg-white rounded-xl">
                    <h2 class="text-1xl">{{item.nome}}</h2>
                    <p class="text-gray-500">R$ {{item.preço}}</p>
                </div>
            </a>
        </div>

        {% endfor %}
    </div>

</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-left">Categorias</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="#">
                <div class="p-6 bg-white rounded-xl">
                    <h2 class="text-1xl">{{category.nome}}</h2>
                    <p class="text-gray-500">{{ category.items.count}} itens</p>
                </div>
            </a>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

puddle/core/templates/core/login.html
{% extends 'core/base.html' %}


{% block title %}
Login
{% endblock title %}


{% block content %}
<div class="max-w-md mx-auto my-8 bg-gray-100 rounded-xl p-4">

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Usuário: </label>
            <br>
            {{form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Senha: </label>
            <br>
            {{form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mx-auto block py-1 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>
</div>
{% endblock content %}

puddle/core/templates/core/signup.html
{% extends 'core/base.html' %}


{% block title %}
Registrar
{% endblock title %}


{% block content %}
<div class="max-w-md mx-auto my-8 bg-gray-100 rounded-xl p-4">

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">E-mail: </label>
            <br>
            {{form.email}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Usuário: </label>
            <br>
            {{form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Senha: </label>
            <br>
            {{form.password1}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirme sua senha: </label>
            <br>
            {{form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mx-auto block py-1 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>
</div>
{% endblock content %}