puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:pk>/", views.detail, name="detail"),
    path("new/<int:item_pk>/", views.new_conversation, name="new"),
]

puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForms
from .views import logout_view


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForms
        ),
        name="login",
    ),
    path("logout/", logout_view, name="logout"),
]

puddle/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
] 

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 

urlpatterns = [
    path("", include('core.urls')), 
    path('inbox/', include('conversation.urls')),
    path("items/", include("item.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User


class Categoria(models.Model):
    nome = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class Item(models.Model):
    categoria = models.ForeignKey(
        Categoria, related_name="items", on_delete=models.CASCADE, default=1
    )
    nome = models.CharField(max_length=255)
    descrição = models.TextField(blank=True, null=True)
    preço = models.FloatField()
    imagem = models.ImageField(upload_to="item_images", blank=True, null=True)
    foi_vendido = models.BooleanField(default=False)
    criado_por = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

puddle/item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = "w-full py-4 px-6 mx-auto rounded-xl p-1 border"


class NewItemForm(forms.ModelForm):

    class Meta:
        model = Item

        fields = (
            "categoria",
            "nome",
            "descrição",
            "preço",
            "imagem",
        )

        widgets = {
            "categoria": forms.Select(attrs={"class": INPUT_CLASSES}),
            "nome": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "descrição": forms.Textarea(attrs={"class": INPUT_CLASSES}),
            "preço": forms.NumberInput(attrs={"class": INPUT_CLASSES}),
            "imagem": forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }


class EditItemForm(forms.ModelForm):

    class Meta:
        model = Item

        fields = (
            "nome",
            "descrição",
            "preço",
            "imagem",
            "foi_vendido",
        )

        widgets = {
            "nome": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "descrição": forms.Textarea(attrs={"class": INPUT_CLASSES}),
            "preço": forms.NumberInput(attrs={"class": INPUT_CLASSES}),
            "imagem": forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }

puddle/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Item, Categoria
from .forms import NewItemForm, EditItemForm


#função para buscarum produto
def items(request):
    query = request.GET.get('query', '')
    categories = Categoria.objects.all()
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(foi_vendido=False)

    if category_id:
        items = items.filter(categoria_id=category_id)

    if query:
        items = items.filter(Q(nome__icontains=query) | Q(descrição__icontains=query))

    return render(request, 'item/items.html', {
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id),
        })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(
        categoria=item.categoria, foi_vendido=False
    ).exclude(pk=pk)[0:3]

    return render(
        request, "item/detail.html", {"item": item, "related_items": related_items}
    )


@login_required
def new(request):

    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item =form.save(commit=False)
            item.criado_por = request.user
            item.save()
            return redirect("item:detail", pk=item.id)
        
    else:    
        form = NewItemForm()
    

    return render(request, "item/form.html", {"form": form, "title": "Novo produto"})

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, criado_por=request.user)
    item.delete()

    return redirect('dashboard:index')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, criado_por=request.user)

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()
            return redirect("item:detail", pk=item.id)
        
    else:    
        form = EditItemForm(instance=item)
    

    return render(request, "item/form.html", {"form": form, "title": "Editar Produto"})

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %}


{% block title %}
{{item.name}}
{% endblock title %}


{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.imagem.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"><strong>{{ item.nome }}</strong></h1>
        <p class="text-gray-700"><strong>R$ {{ item.preço }}</strong></p>
        <p class="text-gray-500"><strong>Criado por: </strong>{{ item.criado_por }}</p>
        <a href="#"
            class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Comprar agora</a>
        <a href="#"
            class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Adicionar ao carrinho</a>
        <br>
        <br>
        {% if item.descrição %}
        <p class="text-gray-700">
            <strong>Descrição: </strong>
            <br>
            {{ item.descrição }}
        </p>
        {% endif %}

        {% if request.user == item.criado_por %} <! se o item for do usuário, pode excluir ou editar>
            <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 text-lg font-semibold bg-red-500 text-white rounded-lg hover:bg-red-700">Excluir anúncio</a>
            <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-700">Editar</a>
        
            {% else %} <! se o item não for do usuário, pode contatar o vendedor>
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-700">Contatar Vendedor</a>
        {% endif %}
        
    </div>
</div>
    {% block content2 %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-left">Ofertas do dia</h2>

        <style>
            /* Estilos CSS */
            .image-container {
                height: 200px;
                /* Defina a altura desejada */
                overflow: hidden;
            }

            .product-image {
                width: 100%;
                height: auto;
                display: block;
                object-fit: fill;
                /* Isso garante que a imagem seja cortada para caber no contêiner */
            }
        </style>

        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div class="image-container">
                        <img src="{{ item.imagem.url }}" class="product-image" alt="{{item.nome}}">
                    </div>

                    <div class="p-6 bg-white rounded-xl">
                        <h2 class="text-1xl">{{item.nome}}</h2>
                        <p class="text-gray-500">R$ {{item.preço}}</p>
                    </div>
                </a>
            </div>

            {% endfor %}
        </div>

    </div>
    {% endblock content2 %}
{% endblock content %}

puddle/item/templates/item/form.html
{% extends 'core/base.html' %}


{% block title %}
{{ title }}
{% endblock title %}


{% block content %}
<h1 class="text-lg font-semibold">{{ title }}</h1>
<br>
<div class="max-w-md mx-auto my-8 bg-gray-100 rounded-xl p-4">
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <br>
        <button
            class="mx-auto block py-1 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>
</div>
{% endblock content %}

puddle/item/templates/item/items.html
{% extends 'core/base.html' %}


{% block title %}
    Items
{% endblock title %}


{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-lg" type="text" value="{{ query }}" placeholder="Pesquisar por um produto">
                <button class="mt-2 py-2 px-6 text-lg bg-teal-500 text-white rounded-lg hover:bg-teal-700">Pesquisar</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categorias</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-lg{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id}}">{{ category.nome }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Limpar Filtros</p>

            <ul>
                <li>
                    <a href="{% url 'item:items' %}" class="mt-2 py-2 px-6 inline-block bg-yellow-500 text-lg rounded-lg text-white hover:bg-yellow-600">Limpar</a>
                </li>
            </ul>

        </div>
        
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="image-container">
                                <img src="{{ item.imagem.url }}" class="product-image" alt="{{item.nome}}">
                            </div>
            
                            <div class="p-6 bg-white rounded-xl">
                                <h2 class="text-1xl">{{item.nome}}</h2>
                                <p class="text-gray-500">R$ {{item.preço}}</p>
                            </div>
                        </a>
                    </div>       
                {% endfor %}
            </div>       
        </div>

    </div>
{% endblock content %}
    
    